name: "Bug Report"
fields:
- type: "textarea"
  attributes:
    label: "Description"
    description: "Give a concise description of the problem"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Expected outcome"
    description: "What did you expect to happen instead?"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Minimal Reproducible Example"
    description: "Provide an example that reproduces the issue, either as a code snippet or a link."
  validations:
    required: true
